name: React Admin Deployment with NGINX

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy React Admin to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: ${{ secrets.PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Starting Vite React deployment..."

            cd /var/www/html/craft/admin || exit 1

            git fetch --all
            git reset --hard origin/main

            rm -rf dist

            npm ci
            npm run build

            chown -R www-data:www-data dist

            systemctl reload nginx

            echo "Deployment completed successfully!"
